### PR TITLE
fix docker issue

### PR DESCRIPTION
**Pull request by hamelsmu**
Fixes https://github.com/github/CodeSearchNet/issues/104

### CODE REVIEW

**Comment by hamelsmu** [comment]
Sadly, I'm still wrestling with this issue.  Kind of stuck, will  take a break and come back to this

**Comment by mallamanis** [comment]
@hamelsmu Would it work if `pip3 install --upgrade PyYAML` instead of using `apt`?

**Comment by Maxscha** [comment]
I am a bit surprised the automatic check failed. The GitHub-Worklfow tests the docker-cpu.docker file and not the docker-gpu.docker file.

**Comment by hamelsmu** [comment]
Indeed this is a mystery to me why all of a sudden things are working, now.

**Pull request closed without merging**
