### PR TITLE
Benchmark Submission: paloukari

### PR DESCRIPTION
**Pull request by paloukari**
This pull request represents a submission to the codesearchnet benchmark. 

 It is the main communication channel for you and the reviewers.

 [Wandb run results for review](https://app.wandb.ai/github/codesearchnet/runs/lbuvsqwt)

### CODE REVIEW

**Comment by mallamanis** [comment]
Hi @paloukari, we had chatted about this via email, but could you please provide a public description of what you did here? If there is any chance that you could show a part of your course report, that would also be amazing.

@hamelsmu This submission works only on Python-related data, but I think it's an interesting exploration in the space. It might be the case that the eval code doesn't handle the absence of the other languages well. We should try to check that.

**Comment by mallamanis** [comment]
Hi @paloukari,

I looked at the `model_predictions.csv` and there seems to be something odd happening:
```
% of URLs in predictions that exist in the annotation dataset:
        python: 0.00%
% of URLs in predictions that exist in the annotation dataset (avg relevance > 0):
        python: 0.00%
```
This suggests that none of the URL in the `model_predictions.csv` appear in our annotated data. I wonder if a a different subset of functions was ranked for some reason. (@hamelsmu any thoughts on what could have gone wrong?)

**Comment by paloukari** [comment]
@mallamanis my project report draft is here: [Comparing_Sequence_based_NLP_Networks_with_Graph_Neural_Networks_in_Semantic_Code_Search](https://github.com/paloukari/W266_Report/blob/master/Comparing_Sequence_based_NLP_Networks_with_Graph_Neural_Networks_in_Semantic_Code_Search.pdf
)
I'm not so sure how I could debug the submitted `model_predictions.csv`, please let me know if you have any ideas.

**Comment by mallamanis** [comment]
Maybe the easiest thing would be to set the `topk` to a large number [here](https://github.com/paloukari/CodeSearchNet/blob/graphs/src/predict.py#L69) and resubmitting the file. 

Skimming through the currently submitted results, I see that the results don't seem very relevant, which is a bit odd. So maybe something else has gone wrong when computing/returning the code representations ([here](https://github.com/paloukari/CodeSearchNet/blob/graphs/src/predict.py#L146))?

**Comment by paloukari** [comment]
Thanks!
will do some research to figure out what's happening here.

**Pull request closed without merging**
