### PR TITLE
Refactor of the Model superclass

### PR DESCRIPTION
**Pull request by vilunov**
- encoder classes are model class fields instead of constructor arguments – the constructor arguments are now sound wrt. subtyping;
- allow different encoder types for different code languages (not tested in practice);
- data, metadata loaders and losses are defined in separate modules.

### CODE REVIEW

**Comment by hamelsmu** [comment]
I am going to close and reopen this PR in order to try to trigger the automated tests

**Comment by hamelsmu** [comment]
@vilunov do you have a full model run with these changes?  Do you have a benchmark submission that uses this refactored code?

**Comment by vilunov** [comment]
https://app.wandb.ai/vilunov/CodeSearchNet/runs/f9yujrgf

Hi @hamelsmu! The run is [here](https://app.wandb.ai/vilunov/CodeSearchNet/runs/f9yujrgf), however, as I'm planning to work further on the code, you may close this PR for the meanwhile, and I'll reopen it after completing my work.

I'm planning to further separate the model itself and various TF and training scaffolding so as not to clutter the model class. Also, I'd like to test models with different types of encoders for different languages.

But if you feel that current changes are good enough, feel free to merge this and I'll open a new PR later.

**Comment by hamelsmu** [comment]
Closing PR for now per suggestion of the author @vilunov.  Feel free to reopen when you are ready for more discussion and review

**Pull request closed without merging**
